-- Add updated_at and updated_by_id audit fields to all catalog tables

ALTER TABLE proyecto
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS updated_by_id UUID REFERENCES users(id) ON DELETE SET NULL DEFAULT NULL;

ALTER TABLE producto
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS updated_by_id UUID REFERENCES users(id) ON DELETE SET NULL DEFAULT NULL;

ALTER TABLE base_de_datos
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS updated_by_id UUID REFERENCES users(id) ON DELETE SET NULL DEFAULT NULL;

ALTER TABLE tabla
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS updated_by_id UUID REFERENCES users(id) ON DELETE SET NULL DEFAULT NULL;

ALTER TABLE instrumento
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS updated_by_id UUID REFERENCES users(id) ON DELETE SET NULL DEFAULT NULL;

ALTER TABLE url
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS updated_by_id UUID REFERENCES users(id) ON DELETE SET NULL DEFAULT NULL;

ALTER TABLE archivo
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS updated_by_id UUID REFERENCES users(id) ON DELETE SET NULL DEFAULT NULL;
