SUPERADMIN = "superadmin"
ADMIN = "admin"
MAINTAINER = "maintainer"
VIEWER = "viewer"
VISUALIZER = "visualizer"

WRITE_ROLES = [ADMIN, MAINTAINER, SUPERADMIN]
ALL_ROLES = [ADMIN, MAINTAINER, VIEWER, VISUALIZER, SUPERADMIN]
