"""baseline schema

Revision ID: 4030e0153505
Revises: 
Create Date: 2026-06-08 12:52:41.781707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4030e0153505'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nombre_corto', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('ambito', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_fuente_oficial', sa.Boolean(), nullable=False),
    sa.Column('es_publicador', sa.Boolean(), nullable=False),
    sa.Column('jurisdiccion', sa.String(), nullable=True),
    sa.Column('url_terminos_uso', sa.Text(), nullable=True),
    sa.Column('url_aviso_privacidad', sa.Text(), nullable=True),
    sa.Column('contacto_institucional', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fuente'))
    )
    op.create_index(op.f('idx_fuente_nombre'), 'fuente', ['nombre'], unique=False)
    op.create_table('permiso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permiso'))
    )
    op.create_table('rol',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rol')),
    sa.UniqueConstraint('nombre', name=op.f('uq_rol_nombre'))
    )
    op.create_table('dataset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nombre_corto', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('identificador_persistente', sa.String(), nullable=True),
    sa.Column('periodicidad', sa.String(), nullable=True),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('url_pagina_principal', sa.Text(), nullable=True),
    sa.Column('url_metodologia_general', sa.Text(), nullable=True),
    sa.Column('url_metadatos_general', sa.Text(), nullable=True),
    sa.Column('desagregacion_geografica', sa.String(), nullable=True),
    sa.Column('cobertura_temporal_general', sa.String(), nullable=True),
    sa.Column('unidad_observacion', sa.String(), nullable=True),
    sa.Column('tema_principal', sa.String(), nullable=True),
    sa.Column('proposito', sa.Text(), nullable=True),
    sa.Column('fecha_inicio_disponibilidad', sa.Date(), nullable=True),
    sa.Column('fecha_fin_disponibilidad', sa.Date(), nullable=True),
    sa.Column('observaciones_dataset', sa.Text(), nullable=True),
    sa.Column('etiquetas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('url_normativa_o_marco_legal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fuente_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuente.id'], name=op.f('fk_dataset_fuente_id_fuente'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset'))
    )
    op.create_index(op.f('idx_dataset_fuente_id'), 'dataset', ['fuente_id'], unique=False)
    op.create_index(op.f('idx_dataset_nombre'), 'dataset', ['nombre'], unique=False)
    op.create_table('permiso_rol',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('permiso_id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], name=op.f('fk_permiso_rol_permiso_id_permiso'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name=op.f('fk_permiso_rol_rol_id_rol'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permiso_rol')),
    sa.UniqueConstraint('permiso_id', 'rol_id', name=op.f('uq_permiso_rol_permiso_id'))
    )
    op.create_index(op.f('idx_permiso_rol_permiso_id'), 'permiso_rol', ['permiso_id'], unique=False)
    op.create_index(op.f('idx_permiso_rol_rol_id'), 'permiso_rol', ['rol_id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rol_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name=op.f('fk_usuario_rol_id_rol'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('correo', name=op.f('uq_usuario_correo'))
    )
    op.create_index(op.f('idx_usuario_rol_id'), 'usuario', ['rol_id'], unique=False)
    op.create_table('base_de_datos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('db_nombre', sa.String(), nullable=False),
    sa.Column('descripcion_esquema', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('fk_base_de_datos_dataset_id_dataset'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_base_de_datos'))
    )
    op.create_index(op.f('idx_base_de_datos_dataset_id'), 'base_de_datos', ['dataset_id'], unique=False)
    op.create_index(op.f('idx_base_de_datos_db_nombre'), 'base_de_datos', ['db_nombre'], unique=False)
    op.create_table('edicion_dataset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('periodo_referencia_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_referencia_fin', sa.Date(), nullable=True),
    sa.Column('tipo_periodo_referencia', sa.String(), nullable=True),
    sa.Column('fecha_levantamiento_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_levantamiento_fin', sa.Date(), nullable=True),
    sa.Column('url_documentacion_edicion', sa.Text(), nullable=True),
    sa.Column('url_comunicado_publicacion', sa.Text(), nullable=True),
    sa.Column('observaciones_edicion', sa.Text(), nullable=True),
    sa.Column('version_publicacion', sa.String(), nullable=True),
    sa.Column('es_version_corregida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('fk_edicion_dataset_dataset_id_dataset'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edicion_dataset'))
    )
    op.create_index(op.f('idx_edicion_dataset_dataset_id'), 'edicion_dataset', ['dataset_id'], unique=False)
    op.create_index(op.f('idx_edicion_dataset_fecha_publicacion'), 'edicion_dataset', ['fecha_publicacion'], unique=False)
    op.create_table('proyecto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_proyecto_usuario_id_usuario'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proyecto'))
    )
    op.create_index(op.f('idx_proyecto_nombre'), 'proyecto', ['nombre'], unique=False)
    op.create_index(op.f('idx_proyecto_usuario_id'), 'proyecto', ['usuario_id'], unique=False)
    op.create_table('distribucion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('descriptor', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('requiere_autenticacion', sa.Boolean(), nullable=False),
    sa.Column('requiere_registro', sa.Boolean(), nullable=False),
    sa.Column('es_url_persistente', sa.Boolean(), nullable=False),
    sa.Column('estado_url_ultima_revision', sa.String(), nullable=True),
    sa.Column('observaciones_distribucion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edicion_dataset_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['edicion_dataset_id'], ['edicion_dataset.id'], name=op.f('fk_distribucion_edicion_dataset_id_edicion_dataset'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distribucion'))
    )
    op.create_index(op.f('idx_distribucion_edicion_dataset_id'), 'distribucion', ['edicion_dataset_id'], unique=False)
    op.create_table('informacion_tablas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_de_datos_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['base_de_datos_id'], ['base_de_datos.id'], name=op.f('fk_informacion_tablas_base_de_datos_id_base_de_datos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_informacion_tablas'))
    )
    op.create_index(op.f('idx_informacion_tablas_base_de_datos_id'), 'informacion_tablas', ['base_de_datos_id'], unique=False)
    op.create_index(op.f('idx_informacion_tablas_nombre'), 'informacion_tablas', ['nombre'], unique=False)
    op.create_table('producto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proyecto_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], name=op.f('fk_producto_proyecto_id_proyecto'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producto'))
    )
    op.create_index(op.f('idx_producto_nombre'), 'producto', ['nombre'], unique=False)
    op.create_index(op.f('idx_producto_proyecto_id'), 'producto', ['proyecto_id'], unique=False)
    op.create_table('archivo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('ruta_relativa_en_distribucion', sa.String(), nullable=True),
    sa.Column('rol_archivo', sa.String(), nullable=True),
    sa.Column('fecha_ingesta_sistema', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('archivos_relacionados', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ruta_almacenamiento', sa.Text(), nullable=True),
    sa.Column('observaciones_archivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distribucion_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['distribucion_id'], ['distribucion.id'], name=op.f('fk_archivo_distribucion_id_distribucion'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archivo'))
    )
    op.create_index(op.f('idx_archivo_distribucion_id'), 'archivo', ['distribucion_id'], unique=False)
    op.create_table('producto_tabla',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha_vinculacion', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('informacion_tablas_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['informacion_tablas_id'], ['informacion_tablas.id'], name=op.f('fk_producto_tabla_informacion_tablas_id_informacion_tablas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('fk_producto_tabla_producto_id_producto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producto_tabla'))
    )
    op.create_index(op.f('idx_producto_tabla_informacion_tablas_id'), 'producto_tabla', ['informacion_tablas_id'], unique=False)
    op.create_index(op.f('idx_producto_tabla_producto_id'), 'producto_tabla', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_producto_tabla_producto_id'), table_name='producto_tabla')
    op.drop_index(op.f('idx_producto_tabla_informacion_tablas_id'), table_name='producto_tabla')
    op.drop_table('producto_tabla')
    op.drop_index(op.f('idx_archivo_distribucion_id'), table_name='archivo')
    op.drop_table('archivo')
    op.drop_index(op.f('idx_producto_proyecto_id'), table_name='producto')
    op.drop_index(op.f('idx_producto_nombre'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('idx_informacion_tablas_nombre'), table_name='informacion_tablas')
    op.drop_index(op.f('idx_informacion_tablas_base_de_datos_id'), table_name='informacion_tablas')
    op.drop_table('informacion_tablas')
    op.drop_index(op.f('idx_distribucion_edicion_dataset_id'), table_name='distribucion')
    op.drop_table('distribucion')
    op.drop_index(op.f('idx_proyecto_usuario_id'), table_name='proyecto')
    op.drop_index(op.f('idx_proyecto_nombre'), table_name='proyecto')
    op.drop_table('proyecto')
    op.drop_index(op.f('idx_edicion_dataset_fecha_publicacion'), table_name='edicion_dataset')
    op.drop_index(op.f('idx_edicion_dataset_dataset_id'), table_name='edicion_dataset')
    op.drop_table('edicion_dataset')
    op.drop_index(op.f('idx_base_de_datos_db_nombre'), table_name='base_de_datos')
    op.drop_index(op.f('idx_base_de_datos_dataset_id'), table_name='base_de_datos')
    op.drop_table('base_de_datos')
    op.drop_index(op.f('idx_usuario_rol_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('idx_permiso_rol_rol_id'), table_name='permiso_rol')
    op.drop_index(op.f('idx_permiso_rol_permiso_id'), table_name='permiso_rol')
    op.drop_table('permiso_rol')
    op.drop_index(op.f('idx_dataset_nombre'), table_name='dataset')
    op.drop_index(op.f('idx_dataset_fuente_id'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_table('rol')
    op.drop_table('permiso')
    op.drop_index(op.f('idx_fuente_nombre'), table_name='fuente')
    op.drop_table('fuente')
    # ### end Alembic commands ###
