name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          changelog-types: '[{"type":"feat","section":"✨ Features"},{"type":"update","section":"🔄 Updates"},{"type":"fix","section":"🐛 Bug Fixes"},{"type":"refactor","section":"♻️ Refactors"},{"type":"chore","section":"🔧 Chores"}]'
